name: egresado_test_jobs
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  execute:
    environment: dev
    env:
      SECRET_OR_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: True
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
      - name: Caches dependencies
        id: caches-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Execute Test
        run: pytest
  build:
    environment: dev
    runs-on: ubuntu-latest
    needs: execute
    env:
      USERNAME: ubuntu
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            whoami
            ls -al
